### PR TITLE
Added debug printer to transmit debug messages over UART for debugging

### PR DESCRIPTION
**Pull request by bristinemuluh**
Added a debug printer to debug over UART.  Still have to fix an issue with format strings. For now only  unformatted or preformatted strings work.

### CODE REVIEW

**Comment by frroossst** [comment]
All this looks very C-esque, did we end up deciding on not using cpp?

**Comment by bristinemuluh** [comment]
How does the code look c-esque lol. because it's in a .c file? I could change that. or because it's not in a class? Not everything needs to be oop. you don't need to create a class for something with no data fields and just one function to interact with.

**Comment by frroossst** [comment]
well you pretty much answered your question, if higher level statemachine is in cpp, then you can just generate a .cpp STM project, else just make everything C. Although it doesn't really matter, just consistency for consistency's sake

**Comment by bristinemuluh** [comment]
I renamed the file to .cpp

**Pull request merged**
